# Generated by Django 3.2 on 2021-06-04 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20210604_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='request',
            field=models.ManyToManyField(related_name='follow_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
