# Generated by Django 3.2 on 2021-06-04 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_profile_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='request',
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_request',
            field=models.ManyToManyField(related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
