# Generated by Django 3.2 on 2021-06-04 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20210604_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend',
        ),
        migrations.AlterField(
            model_name='profile',
            name='follow_request',
            field=models.ManyToManyField(default=None, related_name='request_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='followers_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(default=None, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
