# Generated by Django 3.2 on 2021-06-07 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20210604_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow_request',
            field=models.ManyToManyField(blank=True, related_name='request_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
