# Generated by Django 3.2 on 2021-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210607_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
