# Generated by Django 3.2 on 2021-06-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='private',
            new_name='public',
        ),
    ]
