# Generated by Django 3.2 on 2021-05-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20210504_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='age',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='name',
        ),
    ]
