# Generated by Django 3.2 on 2021-05-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='image',
        ),
    ]
