# Generated by Django 3.2 on 2021-05-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_rename_image_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='no location'),
        ),
    ]
