# Generated by Django 3.2 on 2021-05-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
