# Generated by Django 3.2 on 2021-05-17 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0013_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
