# Generated by Django 3.2 on 2021-05-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_auto_20210517_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
