# Generated by Django 3.2 on 2021-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.CharField(max_length=40),
        ),
    ]
