# Generated by Django 3.2 on 2021-05-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_alter_comment_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
