# Generated by Django 3.2 on 2021-05-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_rename_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='front.post'),
        ),
    ]
