# Generated by Django 3.2 on 2021-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
    ]
