# Generated by Django 3.2 on 2021-06-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0027_alter_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
