# Generated by Django 3.2 on 2021-06-07 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('admin', 'admin'), ('comment', 'comment'), ('like', 'like')], max_length=20)),
                ('notify_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_by', to=settings.AUTH_USER_MODEL)),
                ('notify_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
