# Generated by Django 3.2 on 2021-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_msg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
