# Generated by Django 3.2 on 2021-06-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mark',
            new_name='unread',
        ),
    ]
