# Generated by Django 3.2 on 2021-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20210609_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
